app:
  API_DOMAIN: "localhost"
  kind: development
  PORT: 3333
  API_VERSION: "/v1"

db:
  DATABASE_URL: "postgresql://beeti-dev:cMY46v4nN7hn4MqOE6nZ@localhost:5432/beeti-dev?schema=public"
  DATABASE_KEY: "123"

jwt:
  JWT_SECRET: "privateroute"
  JWT_EXPIRED_IN: "1d"
  API_JWT_ISSUER: beeti

######################################################################
## Configurações YENV ref: https://www.npmjs.com/package/yenv
######################################################################

# Development config uses base config
development:
  # We can compose more than one at a time.
  ~compose: [app, db, jwt]
  # Declare additional settings..
  DEV_MODE: true

# Development config uses base config
test:
  # We can compose more than one at a time.
  ~compose: [app, db, jwt]
  # Declare additional settings..
  DEV_MODE: true

# Production config composes and overrides other sections
production:
  ~compose: development
  DEV_MODE: false
